# This workflow will checkout source code from github respository.
name: checkout source code
on:
  workflow_dispatch:
  workflow_call:
jobs:
  checkout-source-code-job:
    runs-on: [self-hosted, linux, x64, odc, apj]
    steps:
    - name: uppercase
      id: uppercase
      run: |
        GITHUB_USER_ACCOUNT=$(echo $GITHUB_ACTOR | tr '[a-z]' '[A-Z]')
        echo "::set-output name=uppercase_account::$(echo $GITHUB_USER_ACCOUNT)"
    - name: Checkout source code
      id: checkout-source-code
      uses: actions/checkout@v2
      with:
        path: ${{ steps.uppercase.outputs.uppercase_account }}
    - name: Checkout source code result
      if: always() && (steps.checkout-source-code.outcome != 'skipped')
      run: |
        if [[ '${{ steps.checkout-source-code.outcome }}' == 'success' ]]
          then
            echo 'Checkout source code success.'
            echo 'The address of checkout is ${{ github.workspace }}/${{ steps.uppercase.outputs.uppercase_account }}.'
            echo 'Next step will build source code.'
          else
              echo 'Checkout source code failure.'
        fi